instance_groups:
- name: lb
  instances: 1
  vm_type: small
  stemcell: trusty
  azs: []
  networks:
  - name: floating
    static_ips:
    - xxx.xxx.xxx.xx
  - default:
    - dns
    - gateway
    name: default
  jobs:
  - name: nginx
    release: nginx
