---
packages:
- name: nginx
  version: !binary |-
    N2UwZjM0ZTAxOGUzNDQ4M2I4ZmZkY2UyMjY1ODdmMzdjYzdjNjVmZQ==
  fingerprint: !binary |-
    N2UwZjM0ZTAxOGUzNDQ4M2I4ZmZkY2UyMjY1ODdmMzdjYzdjNjVmZQ==
  sha1: !binary |-
    ODU2MTQzZjExZTZjODM1YTk1YThlNzhhOTcwMTAxYWE0NTZkZTBlNg==
  dependencies: []
jobs:
- name: nginx
  version: !binary |-
    YTFkODE5YmU2NDAwMTFjMDRiZTlmOGJmMTQ1ODE3Njg2YzIxYjc0Yg==
  fingerprint: !binary |-
    YTFkODE5YmU2NDAwMTFjMDRiZTlmOGJmMTQ1ODE3Njg2YzIxYjc0Yg==
  sha1: !binary |-
    ZDk1MWE4NTMzZGUzZGM5NmMyMDQyOGJiYjI0Mjk2ZWE3YmMyOTI2MA==
license:
  version: !binary |-
    YzE4M2IxYjgxMjNiYjI2OGE4MTgzMDRjMjNlMmRjZjM3ZmZkMmVlYw==
  fingerprint: !binary |-
    YzE4M2IxYjgxMjNiYjI2OGE4MTgzMDRjMjNlMmRjZjM3ZmZkMmVlYw==
  sha1: !binary |-
    NDE0NWIwYzU5YjExZDBjM2QxYzMwZmFkYjBmMmZjYzdmZmFiZjAxOQ==
commit_hash: 7087e527
uncommitted_changes: true
name: nginx
version: 1.0.5
